### ISSUE TITLE
Words hidden after the green indicator when typed to the bottom-right corner

### ISSUE THREAD

**Issue by hosiet** [retext-project/retext#191]
When I typed to the bottom-right corner of the editor window, the words would be hidden by the green line/column indicator. What's more, selecting words hidden behind becomes impossible.

Should we just move the indicator to the left-bottom corner when the cursor is hovering over the indicator (the same behaviour of Firefox), or move it when words have reached the indicator, or find some other solutions?

Thank you.

**Comment by mitya57** [comment]
You can just add a blank line to the bottom, and scroll to the end of page, can't you?

**Comment by hosiet** [comment]
Sure it's a workaround, but when taking notes constently, all the words are
typed at the bottom line, and this becomes a rather big problem.

**Comment by mitya57** [comment]
I have pushed a commit that (in my opinion) should make it much better. Can you please test it?

**Comment by hosiet** [comment]
Tested, but the commit only changes the transparency of the label. It's still not possible to select texts hidden behind the label :-(

**Comment by mitya57** [comment]
Ok, selection should now work too :)
