### ISSUE TITLE
Link to local file with spaces in name does not work on Linux with Gio

### ISSUE THREAD

**Issue by gkatev** [retext-project/retext#548]
Hi,
I'm having trouble working with links to local files which contain spaces in their names.

In this markdown:
```
[file](file.txt)
[file with spaces](file with spaces.txt)
```
The first link works, while the seconds one outputs an error: (both files exist)
```
gio: file:///home/gkatev/Desktop/file%2520with%2520spaces.txt: Error when getting information for file “/home/gkatev/Desktop/file%20with%20spaces.txt”: No such file or directory
```
Might it be a problem in Retext?
I initially thought it to be a python-qt or gnome-gio error, so I reported it here: (apparently mistakenly so!)
https://bugreports.qt.io/browse/PYSIDE-1488

I *think* the relevant code is the QDesktopServices.openUrl() call at preview.py:49?
In the report, it was suggested that QUrl.fromLocalFile() or QUrl.fromUserInput() should be used instead. (?)

Can you reproduce this issue?
I am on Arch Linux, with Cinnamon as the DE.

**Comment by mitya57** [comment]
Fixed in master, can you please test?

**Comment by gkatev** [comment]
Hm, I'm still getting an error, but a slightly different one. The file it's trying to open contains even more escape codes:
```
gio: file:///home/gkatev/Desktop/file%255C%2520with%255C%2520spaces.txt: Error when getting information for file “/home/gkatev/Desktop/file%5C%20with%5C%20spaces.txt”: No such file or directory
```

**Comment by mitya57** [comment]
Wow, that string in your example is triply percent encoded!

However I cannot reproduce it. Does your Markdown source still contain `[file with spaces](file with spaces.txt)`? Or it is already percent-encoded in Markdown source?

Can you please add some debug prints around this line:
https://github.com/retext-project/retext/blob/995dc3e4af7f868f6046ac1ca498adc312c853a6/ReText/preview.py#L48

and print: the initial value of `link`, the value of `fileToOpen`, and the value of `link` after that line?

**Comment by gkatev** [comment]
Ok ok my bad, I had added some back-slashes in the file name in the MD while testing, and forgot about them!
All works correctly now, thanks
